name: chromedriver test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v2
#    - uses: nanasess/setup-chromedriver@master
    - run: |
        chromedriver --version
